[package]
name = "vdso"
version.workspace = true
edition.workspace = true

[dependencies]
crate_interface = "0.2.0"
axmm.workspace = true
axhal.workspace = true
axalloc.workspace = true
memory_addr.workspace = true
axlog.workspace = true
axerrno.workspace = true
axsync.workspace = true

# libvsched2 = { path = "../vdso_vsched2_output/libvsched2" }
libvqueue = { path = "../vdso_vqueue_output/libvqueue" }

[build-dependencies]
# build_vdso = { path = "../../vdso_crate_template/vdso_crate_template/build_vdso" }
build_vdso = { git = "https://github.com/rosy233333/vdso_crate_template", package = "build_vdso" }