[package]
name = "vdso"
version.workspace = true
edition.workspace = true

[dependencies]
libvsched2 = { path = "../vdso_vsched2_output/libvsched2" }
libstarry_vsched = { path = "../vdso_starry_vsched_output/libstarry_vsched" }
crate_interface = "0.2.0"
axmm.workspace = true
axhal.workspace = true
axalloc.workspace = true
memory_addr.workspace = true
axlog.workspace = true
axerrno.workspace = true
axsync.workspace = true
include_bytes_aligned = "0.1.4"
xmas-elf = "0.9"

[build-dependencies]
build_vdso = { path = "../../vdso_crate_template/vdso_crate_template/build_vdso" }
