[package]
name = "libvqueue"
edition = "2021"

[dependencies]
vqueue = { path = "../../deps/vqueue_vdso" }
log = { version = "0.4" }
crate_interface = "0.2"
page_table_entry = "0.5.7"
include_bytes_aligned = "0.1.4"
xmas-elf = "0.9.0"
elf_parser = { path = "../../deps/elf_parser" }
lazyinit = "0.2"

[features]
log = []
default = []
